services:
  - type: web
    name: fastfood-delicia
    env: java
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/bd-0.0.1-SNAPSHOT.jar --debug
    envVars:
      - key: DB_URL
      - key: DB_USERNAME
      - key: DB_PASSWORD